image: maven:latest

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository/"
  GIT_SSL_NO_VERIFY: "true"
 
deploy:
  stage: deploy
  script:
    - (cd "./tourPlanningLibrary/" && mvn deploy)
    - (cd "./tourPlanningLibrary-mvn-repo/" && git init)
    - (cd "./tourPlanningLibrary-mvn-repo/" && git remote add origin git@git.e-science.pl:pjasiczek225933/81c_PJasiczek_Maven.git)
    - (cd "./tourPlanningLibrary-mvn-repo/" && git fetch -p)
    - (cd "./tourPlanningLibrary-mvn-repo/" && git checkout -b GitLab-Runner)
    - (cd "./tourPlanningLibrary-mvn-repo/" && git add -A)
    - (cd "./tourPlanningLibrary-mvn-repo/" && git commit -m "add GitLabRunner")
    - (cd "./tourPlanningLibrary-mvn-repo/" && git push origin GitLab-Runner)
  only:
   - biblioteka
